services:
  mysql:
    image: mysql:8.0
    container_name: restaurante_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: restaurante_db
      MYSQL_USER: restaurante_user
      MYSQL_PASSWORD: restaurante123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data:
